-- MySQL Script generated by MySQL Workbench
-- Sat Apr  2 15:29:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport` (
  `airport_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `global_id` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`airport_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Model` (
  `constructor's_name` VARCHAR(45) NOT NULL,
  `seats` INT NOT NULL,
  `weight` INT NOT NULL,
  PRIMARY KEY (`constructor's_name`, `seats`, `weight`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aircraft` (
  `registration_id` INT NOT NULL,
  `Model_constructor's_name` VARCHAR(45) NOT NULL,
  `Model_seats` INT NOT NULL,
  `Model_weight` INT NOT NULL,
  PRIMARY KEY (`registration_id`),
  INDEX `fk_Aircraft_Model1_idx` (`Model_constructor's_name` ASC, `Model_seats` ASC, `Model_weight` ASC) VISIBLE,
  CONSTRAINT `fk_Aircraft_Model1`
    FOREIGN KEY (`Model_constructor's_name` , `Model_seats` , `Model_weight`)
    REFERENCES `mydb`.`Model` (`constructor's_name` , `seats` , `weight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airline` (
  `airline_global_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`airline_global_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `menu_id` INT NOT NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight` (
  `departure_datetime` DATETIME NOT NULL,
  `aircraft_id` INT NOT NULL,
  `arrival_datetime` DATETIME NOT NULL,
  `airline_global_id` INT NOT NULL,
  `departure_airport_id` INT NOT NULL,
  `arrival_airport_id` INT NOT NULL,
  `menu_id` INT NOT NULL,
  PRIMARY KEY (`departure_datetime`, `aircraft_id`),
  INDEX `fk_Flight_Airline_idx` (`airline_global_id` ASC) VISIBLE,
  INDEX `fk_Flight_Airport1_idx` (`departure_airport_id` ASC) VISIBLE,
  INDEX `fk_Flight_Airport2_idx` (`arrival_airport_id` ASC) VISIBLE,
  INDEX `fk_Flight_Aircraft1_idx` (`aircraft_id` ASC) VISIBLE,
  INDEX `fk_Flight_Menu1_idx` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `fk_Flight_Airline`
    FOREIGN KEY (`airline_global_id`)
    REFERENCES `mydb`.`Airline` (`airline_global_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airport1`
    FOREIGN KEY (`departure_airport_id`)
    REFERENCES `mydb`.`Airport` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Airport2`
    FOREIGN KEY (`arrival_airport_id`)
    REFERENCES `mydb`.`Airport` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Aircraft1`
    FOREIGN KEY (`aircraft_id`)
    REFERENCES `mydb`.`Aircraft` (`registration_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `mydb`.`Menu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airport_serves_Airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport_serves_Airline` (
  `airport_id` INT NOT NULL,
  `airline_global_id` INT NOT NULL,
  PRIMARY KEY (`airport_id`, `airline_global_id`),
  INDEX `fk_Airport_has_Airline_Airline1_idx` (`airline_global_id` ASC) VISIBLE,
  INDEX `fk_Airport_has_Airline_Airport1_idx` (`airport_id` ASC) VISIBLE,
  CONSTRAINT `fk_Airport_has_Airline_Airport1`
    FOREIGN KEY (`airport_id`)
    REFERENCES `mydb`.`Airport` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airport_has_Airline_Airline1`
    FOREIGN KEY (`airline_global_id`)
    REFERENCES `mydb`.`Airline` (`airline_global_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dish` (
  `dish_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dish_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seat` (
  `seat_type` ENUM('FC', 'BC', 'PE', 'EC') NOT NULL,
  PRIMARY KEY (`seat_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`combination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`combination` (
  `seat_type` ENUM('FC', 'BC', 'PE', 'EC') NOT NULL,
  `dish_name` VARCHAR(45) NOT NULL,
  `menu_id` INT NOT NULL,
  PRIMARY KEY (`dish_name`, `menu_id`, `seat_type`),
  INDEX `fk_Seat_has_Dishes_Dishes1_idx` (`dish_name` ASC) VISIBLE,
  INDEX `fk_Seat_has_Dishes_Seat1_idx` (`seat_type` ASC) VISIBLE,
  INDEX `fk_combination_Menu1_idx` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `fk_Seat_has_Dishes_Seat1`
    FOREIGN KEY (`seat_type`)
    REFERENCES `mydb`.`Seat` (`seat_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seat_has_Dishes_Dishes1`
    FOREIGN KEY (`dish_name`)
    REFERENCES `mydb`.`Dish` (`dish_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_combination_Menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `mydb`.`Menu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `full_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `person_key` INT NOT NULL,
  PRIMARY KEY (`person_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccination_certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccination_certificate` (
  `id_vaccination_certificate` INT NOT NULL,
  `number_of_doses` INT NOT NULL,
  `last_dose` DATETIME NOT NULL,
  PRIMARY KEY (`id_vaccination_certificate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passenger` (
  `passport_id` INT NOT NULL,
  `person_key` INT NOT NULL,
  `vaccination_certificate_id` INT NOT NULL,
  PRIMARY KEY (`passport_id`),
  INDEX `fk_Passenger_Person1_idx` (`person_key` ASC) VISIBLE,
  INDEX `fk_Passenger_vaccination_certificate1_idx` (`vaccination_certificate_id` ASC) VISIBLE,
  CONSTRAINT `fk_Passenger_Person1`
    FOREIGN KEY (`person_key`)
    REFERENCES `mydb`.`Person` (`person_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Passenger_vaccination_certificate1`
    FOREIGN KEY (`vaccination_certificate_id`)
    REFERENCES `mydb`.`Vaccination_certificate` (`id_vaccination_certificate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Website`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Website` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `qr_code` INT NOT NULL,
  `ticket_id` INT NOT NULL,
  `purchase_date` DATE NOT NULL,
  `passport_id` INT NOT NULL,
  `aircraft_id` INT NOT NULL,
  `departure_datetime` DATETIME NOT NULL,
  `Website_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `fk_Ticket_Passenger1_idx` (`passport_id` ASC) VISIBLE,
  INDEX `fk_Ticket_Flight1_idx` (`aircraft_id` ASC, `departure_datetime` ASC) VISIBLE,
  INDEX `fk_Ticket_Website1_idx` (`Website_name` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Passenger1`
    FOREIGN KEY (`passport_id`)
    REFERENCES `mydb`.`Passenger` (`passport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Flight1`
    FOREIGN KEY (`aircraft_id` , `departure_datetime`)
    REFERENCES `mydb`.`Flight` (`aircraft_id` , `departure_datetime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Website1`
    FOREIGN KEY (`Website_name`)
    REFERENCES `mydb`.`Website` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Research`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Research` (
  `person_key` INT NOT NULL,
  `Flight_departure_datetime` DATETIME NOT NULL,
  `Flight_aircraft_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `general_information` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`person_key`, `Flight_departure_datetime`, `Flight_aircraft_id`),
  INDEX `fk_Research_Person1_idx` (`person_key` ASC) VISIBLE,
  INDEX `fk_Research_Flight1_idx` (`Flight_departure_datetime` ASC, `Flight_aircraft_id` ASC) VISIBLE,
  CONSTRAINT `fk_Research_Person1`
    FOREIGN KEY (`person_key`)
    REFERENCES `mydb`.`Person` (`person_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Research_Flight1`
    FOREIGN KEY (`Flight_departure_datetime` , `Flight_aircraft_id`)
    REFERENCES `mydb`.`Flight` (`departure_datetime` , `aircraft_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Manifest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manifest` (
  `Flight_aircraft_id` INT NOT NULL,
  `Flight_departure_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`Flight_aircraft_id`, `Flight_departure_datetime`),
  INDEX `fk_Manifest_Flight2_idx` (`Flight_aircraft_id` ASC, `Flight_departure_datetime` ASC) VISIBLE,
  CONSTRAINT `fk_Manifest_Flight2`
    FOREIGN KEY (`Flight_aircraft_id` , `Flight_departure_datetime`)
    REFERENCES `mydb`.`Flight` (`aircraft_id` , `departure_datetime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `reservation_id` INT NOT NULL,
  `passport_id` INT NOT NULL,
  `person_key` INT NOT NULL,
  `seat_type` ENUM('FC', 'BC', 'PE', 'EC') NOT NULL,
  `reservation_date` DATE NOT NULL,
  `comments` VARCHAR(45) NULL,
  `Website_name` VARCHAR(45) NOT NULL,
  `Manifest_Flight_aircraft_id` INT NOT NULL,
  `Manifest_Flight_departure_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `fk_Reservation_Passenger1_idx` (`passport_id` ASC, `person_key` ASC) VISIBLE,
  INDEX `fk_Reservation_Seat1_idx` (`seat_type` ASC) VISIBLE,
  INDEX `fk_Reservation_Website1_idx` (`Website_name` ASC) VISIBLE,
  INDEX `fk_Reservation_Manifest1_idx` (`Manifest_Flight_aircraft_id` ASC, `Manifest_Flight_departure_datetime` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Passenger1`
    FOREIGN KEY (`passport_id` , `person_key`)
    REFERENCES `mydb`.`Passenger` (`passport_id` , `person_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Seat1`
    FOREIGN KEY (`seat_type`)
    REFERENCES `mydb`.`Seat` (`seat_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Website1`
    FOREIGN KEY (`Website_name`)
    REFERENCES `mydb`.`Website` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Manifest1`
    FOREIGN KEY (`Manifest_Flight_aircraft_id` , `Manifest_Flight_departure_datetime`)
    REFERENCES `mydb`.`Manifest` (`Flight_aircraft_id` , `Flight_departure_datetime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Union`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Union` (
  `name` VARCHAR(45) NOT NULL,
  `since:` INT NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `identity` INT NOT NULL,
  `person_key` INT NOT NULL,
  `Airport_airport_id` INT NOT NULL,
  `Union_name` VARCHAR(45) NOT NULL,
  INDEX `fk_Employee_Person1_idx` (`person_key` ASC) VISIBLE,
  INDEX `fk_Employee_Airport1_idx` (`Airport_airport_id` ASC) VISIBLE,
  INDEX `fk_Employee_Union1_idx` (`Union_name` ASC) VISIBLE,
  PRIMARY KEY (`identity`),
  CONSTRAINT `fk_Employee_Person1`
    FOREIGN KEY (`person_key`)
    REFERENCES `mydb`.`Person` (`person_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Airport1`
    FOREIGN KEY (`Airport_airport_id`)
    REFERENCES `mydb`.`Airport` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Union1`
    FOREIGN KEY (`Union_name`)
    REFERENCES `mydb`.`Union` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technitian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technitian` (
  `salary` INT NOT NULL,
  `Employee_identity` INT NOT NULL,
  PRIMARY KEY (`Employee_identity`),
  INDEX `fk_Technitian_Employee1_idx` (`Employee_identity` ASC) VISIBLE,
  CONSTRAINT `fk_Technitian_Employee1`
    FOREIGN KEY (`Employee_identity`)
    REFERENCES `mydb`.`Employee` (`identity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Air Traffic Controller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Air Traffic Controller` (
  `last_medical_check` DATE NOT NULL,
  `Employee_identity` INT NOT NULL,
  PRIMARY KEY (`Employee_identity`),
  INDEX `fk_Air Traffic Controller_Employee1_idx` (`Employee_identity` ASC) VISIBLE,
  CONSTRAINT `fk_Air Traffic Controller_Employee1`
    FOREIGN KEY (`Employee_identity`)
    REFERENCES `mydb`.`Employee` (`identity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Test` (
  `YPA_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `max_score` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`YPA_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airport_has_Aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport_has_Aircraft` (
  `airport_id` INT NOT NULL,
  `Aircraft_registration_id` INT NOT NULL,
  PRIMARY KEY (`airport_id`, `Aircraft_registration_id`),
  INDEX `fk_Airport_has_Aircraft_Aircraft2_idx` (`Aircraft_registration_id` ASC) VISIBLE,
  INDEX `fk_Airport_has_Aircraft_Airport2_idx` (`airport_id` ASC) VISIBLE,
  CONSTRAINT `fk_Airport_has_Aircraft_Airport2`
    FOREIGN KEY (`airport_id`)
    REFERENCES `mydb`.`Airport` (`airport_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airport_has_Aircraft_Aircraft2`
    FOREIGN KEY (`Aircraft_registration_id`)
    REFERENCES `mydb`.`Aircraft` (`registration_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Website_has_Research`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Website_has_Research` (
  `Website_name` VARCHAR(45) NOT NULL,
  `Research_person_key` INT NOT NULL,
  `Research_Flight_departure_datetime` DATETIME NOT NULL,
  `Research_Flight_aircraft_id` INT NOT NULL,
  PRIMARY KEY (`Website_name`, `Research_person_key`, `Research_Flight_departure_datetime`, `Research_Flight_aircraft_id`),
  INDEX `fk_Website_has_Research_Research1_idx` (`Research_person_key` ASC, `Research_Flight_departure_datetime` ASC, `Research_Flight_aircraft_id` ASC) VISIBLE,
  INDEX `fk_Website_has_Research_Website1_idx` (`Website_name` ASC) VISIBLE,
  CONSTRAINT `fk_Website_has_Research_Website1`
    FOREIGN KEY (`Website_name`)
    REFERENCES `mydb`.`Website` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Website_has_Research_Research1`
    FOREIGN KEY (`Research_person_key` , `Research_Flight_departure_datetime` , `Research_Flight_aircraft_id`)
    REFERENCES `mydb`.`Research` (`person_key` , `Flight_departure_datetime` , `Flight_aircraft_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technitian_test_aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technitian_test_aircraft` (
  `hours` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `score` VARCHAR(45) NOT NULL,
  `Technitian_Employee_identity` INT NOT NULL,
  `Test_YPA_id` INT NOT NULL,
  `Aircraft_registration_id` INT NOT NULL,
  PRIMARY KEY (`Technitian_Employee_identity`, `Test_YPA_id`, `Aircraft_registration_id`),
  INDEX `fk_Technitian_test_aircraft_Technitian1_idx` (`Technitian_Employee_identity` ASC) VISIBLE,
  INDEX `fk_Technitian_test_aircraft_Test1_idx` (`Test_YPA_id` ASC) VISIBLE,
  INDEX `fk_Technitian_test_aircraft_Aircraft1_idx` (`Aircraft_registration_id` ASC) VISIBLE,
  CONSTRAINT `fk_Technitian_test_aircraft_Technitian1`
    FOREIGN KEY (`Technitian_Employee_identity`)
    REFERENCES `mydb`.`Technitian` (`Employee_identity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technitian_test_aircraft_Test1`
    FOREIGN KEY (`Test_YPA_id`)
    REFERENCES `mydb`.`Test` (`YPA_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technitian_test_aircraft_Aircraft1`
    FOREIGN KEY (`Aircraft_registration_id`)
    REFERENCES `mydb`.`Aircraft` (`registration_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technician_specifies_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technician_specifies_model` (
  `Model_constructor's_name` VARCHAR(45) NOT NULL,
  `Model_seats` INT NOT NULL,
  `Model_weight` INT NOT NULL,
  `Technitian_Employee_identity` INT NOT NULL,
  PRIMARY KEY (`Model_constructor's_name`, `Model_seats`, `Model_weight`, `Technitian_Employee_identity`),
  INDEX `fk_Model_has_Technitian_Technitian1_idx` (`Technitian_Employee_identity` ASC) VISIBLE,
  INDEX `fk_Model_has_Technitian_Model1_idx` (`Model_constructor's_name` ASC, `Model_seats` ASC, `Model_weight` ASC) VISIBLE,
  CONSTRAINT `fk_Model_has_Technitian_Model1`
    FOREIGN KEY (`Model_constructor's_name` , `Model_seats` , `Model_weight`)
    REFERENCES `mydb`.`Model` (`constructor's_name` , `seats` , `weight`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Model_has_Technitian_Technitian1`
    FOREIGN KEY (`Technitian_Employee_identity`)
    REFERENCES `mydb`.`Technitian` (`Employee_identity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
